### GET
GET http://localhost:5008/

###

### GET steden
GET http://localhost:5008/steden

###
###
GET http://localhost:5008/weerstations
###


###
GET http://localhost:5008/metingen
###

###
POST http://localhost:5008/commandsmetingen
###

GET http://localhost:5008/weerbericht